

color0 #4c4639
color1 #ffb4ab
color2 #e6c36c
color3 #d6c5a0
color4 #aecfac
color5 #e6c36c
color6 #d6c5a0
color7 #eae1d4
color8 #989080
color9 #ffb4ab
color10 #e6c36c
color11 #d6c5a0
color12 #aecfac
color13 #e6c36c
color14 #d6c5a0
color15 #eae1d4

# BEGIN_KITTY_FONTS
font_family Hack Nerd Font Bold
bold_font Hack Nerd Font Bold
italic_font Hack Nerd Font Italic
bold_italic_font Hack Nerd Font Bold Italic
# END_KITTY_FONTS

font_size 20
cursor                #eae1d4
cursor_text_color     #16130b
cursor_trail 10
cursor_trail_decay 0.025 0.15
cursor_trail_start_threshold 1

background_opacity 0.75
background_blur 1

include themes/noctalia.conf
